import type { ImageSourcePropType } from 'react-native';

export const Icons = {
  bantayLogo: require('@/assets/Icons/BantayLogo.png'),
  camera: require('@/assets/Icons/Camera.png'),
  cloudyDay: require('@/assets/Icons/CloudyDay.png'),
  comment: require('@/assets/Icons/Comment.png'),
  darkMode: require('@/assets/Icons/DarkMode.png'),
  darkModeActive: require('@/assets/Icons/DarkMode-Active.png'),
  defaultProfile: require('@/assets/Icons/Default Profile.png'),
  dswd: require('@/assets/Icons/DSWD.png'),
  earthquake: require('@/assets/Icons/EarthquakeIcon.png'),
  earthquakeWhite: require('@/assets/Icons/EarthquakeIconWhite.png'),
  edit: require('@/assets/Icons/EditIcon.png'),
  engineering: require('@/assets/Icons/EngineeringDep.png'),
  evacuation: require('@/assets/Icons/Evacuation.png'),
  evacuationBlue: require('@/assets/Icons/EvacuationBlue.png'),
  failed: require('@/assets/Icons/Failed.png'),
  filter: require('@/assets/Icons/FilterIcon.png'),
  fire: require('@/assets/Icons/FireIcon.png'),
  fireWhite: require('@/assets/Icons/FireIconWhite.png'),
  fireDepartment: require('@/assets/Icons/FireDep.png'),
  flood: require('@/assets/Icons/Flood.png'),
  floodWhite: require('@/assets/Icons/FloodIconWhite.png'),
  health: require('@/assets/Icons/HealthDep.png'),
  heat: require('@/assets/Icons/HeatIcon.png'),
  home: require('@/assets/Icons/Home.png'),
  homeDark: require('@/assets/Icons/homeDark.png'),
  homeActive: require('@/assets/Icons/Home (2).png'),
  hotline: require('@/assets/Icons/Hotline.png'),
  hotlineRed: require('@/assets/Icons/HotlineRed.png'),
  landslide: require('@/assets/Icons/LandslideIcon.png'),
  landslideWhite: require('@/assets/Icons/LandslideIconWhite.png'),
  lightMode: require('@/assets/Icons/LightMode.png'),
  lightModeActive: require('@/assets/Icons/LightMode-Active.png'),
  like: require('@/assets/Icons/Like.png'),
  likeActive: require('@/assets/Icons/Like-Active.png'),
  map: require('@/assets/Icons/Map.png'),
  mapDark: require('@/assets/Icons/mapDark.png'),
  mapActive: require('@/assets/Icons/Map (2).png'),
  notification: require('@/assets/Icons/Notification.png'),
  notificationDark: require('@/assets/Icons/notificationDark.png'),
  notificationActive: require('@/assets/Icons/Notification-Active.png'),
  office: require('@/assets/Icons/Office.png'),
  othersWhite: require('@/assets/Icons/OthersIconWhite.png'), 
  pin: require('@/assets/Icons/Pin.png'),
  police: require('@/assets/Icons/PolicePNPDep.png'),
  powerOutageWhite: require('@/assets/Icons/PowerOutageIconWhite.png'),
  profile: require('@/assets/Icons/ProfileIcon.png'),
  profileDark: require('@/assets/Icons/profileDark.png'),
  profileActive: require('@/assets/Icons/ProfileIcon-Active.png'),
  rainyDay: require('@/assets/Icons/RainyDay.png'),
  redFlag: require('@/assets/Icons/RedFlag.png'),
  report: require('@/assets/Icons/Report.png'),
  reportInactive: require('@/assets/Icons/HazardReport.png'),
  roadBlockageWhite: require('@/assets/Icons/RoadBlockageIconWhite.png'),
  safetyTips: require('@/assets/Icons/SafetyTips.png'),
  success: require('@/assets/Icons/Success.png'),
  sunnyDay: require('@/assets/Icons/SunnyDay.png'),
  typhoon: require('@/assets/Icons/Typhoon.png'),
  water: require('@/assets/Icons/Water.png'),
} satisfies Record<string, ImageSourcePropType>;

export const preloadIconAssets = Object.values(Icons);
